name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run E2E tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  # Fast UI tests with mocked backend - runs on every PR
  ui-tests:
    name: UI Tests (Mocked)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run UI tests (mocked)
        run: npx playwright test --project ui-mocked
      
      - name: Upload UI test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  # Accessibility tests - runs on every PR
  a11y-tests:
    name: Accessibility Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run accessibility tests
        run: npx playwright test --project a11y-live
      
      - name: Upload A11y test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: a11y-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  # E2E tests with live backend - runs on schedule and main branch
  e2e-tests:
    name: E2E Tests (Live)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run E2E tests (live)
        run: npx playwright test --project e2e-live
        env:
          # Add any required environment variables for E2E tests
          CHESS_BASE_URL: https://www.chess.com
      
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  # Test summary
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [ui-tests, a11y-tests, e2e-tests]
    if: always()
    steps:
      - name: Check test results
        run: |
          echo "UI Tests: ${{ needs.ui-tests.result }}"
          echo "A11y Tests: ${{ needs.a11y-tests.result }}"
          echo "E2E Tests: ${{ needs.e2e-tests.result }}"
